# Generated by carnix 0.10.0: carnix generate-nix --src ./.
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# laptop-stats-0.1.0

    crates.laptop_stats."0.1.0" = deps: { features?(features_.laptop_stats."0.1.0" deps {}) }: buildRustCrate {
      crateName = "laptop-stats";
      version = "0.1.0";
      authors = [ "Benjamin Herr <ben@0x539.de>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."failure"."${deps."laptop_stats"."0.1.0"."failure"}" deps)
        (cratesIO.crates."hyper"."${deps."laptop_stats"."0.1.0"."hyper"}" deps)
        (cratesIO.crates."prometheus"."${deps."laptop_stats"."0.1.0"."prometheus"}" deps)
        (cratesIO.crates."structopt"."${deps."laptop_stats"."0.1.0"."structopt"}" deps)
      ]);
    };
    features_.laptop_stats."0.1.0" = deps: f: updateFeatures f (rec {
      failure."${deps.laptop_stats."0.1.0".failure}".default = true;
      hyper."${deps.laptop_stats."0.1.0".hyper}".default = true;
      laptop_stats."0.1.0".default = (f.laptop_stats."0.1.0".default or true);
      prometheus."${deps.laptop_stats."0.1.0".prometheus}".default = true;
      structopt."${deps.laptop_stats."0.1.0".structopt}".default = true;
    }) [
      (cratesIO.features_.failure."${deps."laptop_stats"."0.1.0"."failure"}" deps)
      (cratesIO.features_.hyper."${deps."laptop_stats"."0.1.0"."hyper"}" deps)
      (cratesIO.features_.prometheus."${deps."laptop_stats"."0.1.0"."prometheus"}" deps)
      (cratesIO.features_.structopt."${deps."laptop_stats"."0.1.0"."structopt"}" deps)
    ];


# end

  };

  laptop_stats = crates.crates.laptop_stats."0.1.0" deps;
  __all = [ (laptop_stats {}) ];
  deps.ansi_term."0.10.2" = {};
  deps.atty."0.2.10" = {
    termion = "1.5.1";
    libc = "0.2.35";
    winapi = "0.3.3";
  };
  deps.backtrace."0.3.5" = {
    cfg_if = "0.1.2";
    rustc_demangle = "0.1.5";
    backtrace_sys = "0.1.16";
    libc = "0.2.35";
    winapi = "0.3.3";
  };
  deps.backtrace_sys."0.1.16" = {
    libc = "0.2.35";
    cc = "1.0.3";
  };
  deps.base64."0.9.0" = {
    byteorder = "1.2.1";
    safemem = "0.2.0";
  };
  deps.bitflags."0.7.0" = {};
  deps.bitflags."1.0.1" = {};
  deps.byteorder."1.2.1" = {};
  deps.bytes."0.4.5" = {
    byteorder = "1.2.1";
    iovec = "0.1.1";
  };
  deps.cc."1.0.3" = {};
  deps.cfg_if."0.1.2" = {};
  deps.clap."2.30.0" = {
    atty = "0.2.10";
    bitflags = "1.0.1";
    strsim = "0.7.0";
    textwrap = "0.9.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.10.2";
  };
  deps.failure."0.1.1" = {
    backtrace = "0.3.5";
    failure_derive = "0.1.1";
  };
  deps.failure_derive."0.1.1" = {
    quote = "0.3.15";
    syn = "0.11.11";
    synstructure = "0.6.1";
  };
  deps.fnv."1.0.6" = {};
  deps.fuchsia_zircon."0.2.1" = {
    fuchsia_zircon_sys = "0.2.0";
  };
  deps.fuchsia_zircon."0.3.2" = {
    bitflags = "1.0.1";
    fuchsia_zircon_sys = "0.3.2";
  };
  deps.fuchsia_zircon_sys."0.2.0" = {
    bitflags = "0.7.0";
  };
  deps.fuchsia_zircon_sys."0.3.2" = {};
  deps.futures."0.1.17" = {};
  deps.futures_cpupool."0.1.8" = {
    futures = "0.1.17";
    num_cpus = "1.8.0";
  };
  deps.httparse."1.2.3" = {};
  deps.hyper."0.11.10" = {
    base64 = "0.9.0";
    bytes = "0.4.5";
    futures = "0.1.17";
    futures_cpupool = "0.1.8";
    httparse = "1.2.3";
    language_tags = "0.2.2";
    log = "0.3.9";
    mime = "0.3.5";
    percent_encoding = "1.0.1";
    relay = "0.1.0";
    time = "0.1.39";
    tokio_core = "0.1.11";
    tokio_io = "0.1.4";
    tokio_proto = "0.1.1";
    tokio_service = "0.1.0";
    unicase = "2.1.0";
  };
  deps.iovec."0.1.1" = {
    libc = "0.2.35";
    winapi = "0.2.8";
  };
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.language_tags."0.2.2" = {};
  deps.laptop_stats."0.1.0" = {
    failure = "0.1.1";
    hyper = "0.11.10";
    prometheus = "0.3.6";
    structopt = "0.2.10";
  };
  deps.lazy_static."0.2.11" = {};
  deps.lazycell."0.5.1" = {};
  deps.libc."0.2.35" = {};
  deps.log."0.3.9" = {
    log = "0.4.1";
  };
  deps.log."0.4.1" = {
    cfg_if = "0.1.2";
  };
  deps.mime."0.3.5" = {
    unicase = "2.1.0";
  };
  deps.mio."0.6.11" = {
    iovec = "0.1.1";
    lazycell = "0.5.1";
    log = "0.3.9";
    net2 = "0.2.31";
    slab = "0.3.0";
    fuchsia_zircon = "0.2.1";
    fuchsia_zircon_sys = "0.2.0";
    libc = "0.2.35";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.31";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.net2."0.2.31" = {
    cfg_if = "0.1.2";
    libc = "0.2.35";
    kernel32_sys = "0.2.2";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.num_cpus."1.8.0" = {
    libc = "0.2.35";
  };
  deps.percent_encoding."1.0.1" = {};
  deps.proc_macro2."0.4.6" = {
    unicode_xid = "0.1.0";
  };
  deps.prometheus."0.3.6" = {
    cfg_if = "0.1.2";
    fnv = "1.0.6";
    lazy_static = "0.2.11";
    protobuf = "1.4.3";
    quick_error = "0.2.2";
    spin = "0.4.6";
  };
  deps.protobuf."1.4.3" = {};
  deps.quick_error."0.2.2" = {};
  deps.quote."0.3.15" = {};
  deps.quote."0.6.3" = {
    proc_macro2 = "0.4.6";
  };
  deps.rand."0.3.19" = {
    libc = "0.2.35";
    fuchsia_zircon = "0.3.2";
  };
  deps.redox_syscall."0.1.34" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.34";
  };
  deps.relay."0.1.0" = {
    futures = "0.1.17";
  };
  deps.rustc_demangle."0.1.5" = {};
  deps.safemem."0.2.0" = {};
  deps.scoped_tls."0.1.0" = {};
  deps.slab."0.3.0" = {};
  deps.slab."0.4.0" = {};
  deps.smallvec."0.2.1" = {};
  deps.spin."0.4.6" = {};
  deps.strsim."0.7.0" = {};
  deps.structopt."0.2.10" = {
    clap = "2.30.0";
    structopt_derive = "0.2.10";
  };
  deps.structopt_derive."0.2.10" = {
    proc_macro2 = "0.4.6";
    quote = "0.6.3";
    syn = "0.14.2";
  };
  deps.syn."0.11.11" = {
    quote = "0.3.15";
    synom = "0.11.3";
    unicode_xid = "0.0.4";
  };
  deps.syn."0.14.2" = {
    proc_macro2 = "0.4.6";
    quote = "0.6.3";
    unicode_xid = "0.1.0";
  };
  deps.synom."0.11.3" = {
    unicode_xid = "0.0.4";
  };
  deps.synstructure."0.6.1" = {
    quote = "0.3.15";
    syn = "0.11.11";
  };
  deps.take."0.1.0" = {};
  deps.termion."1.5.1" = {
    libc = "0.2.35";
    redox_syscall = "0.1.34";
    redox_termios = "0.1.1";
  };
  deps.textwrap."0.9.0" = {
    unicode_width = "0.1.5";
  };
  deps.time."0.1.39" = {
    libc = "0.2.35";
    redox_syscall = "0.1.34";
    winapi = "0.3.3";
  };
  deps.tokio_core."0.1.11" = {
    bytes = "0.4.5";
    futures = "0.1.17";
    iovec = "0.1.1";
    log = "0.3.9";
    mio = "0.6.11";
    scoped_tls = "0.1.0";
    slab = "0.4.0";
    tokio_io = "0.1.4";
  };
  deps.tokio_io."0.1.4" = {
    bytes = "0.4.5";
    futures = "0.1.17";
    log = "0.3.9";
  };
  deps.tokio_proto."0.1.1" = {
    futures = "0.1.17";
    log = "0.3.9";
    net2 = "0.2.31";
    rand = "0.3.19";
    slab = "0.3.0";
    smallvec = "0.2.1";
    take = "0.1.0";
    tokio_core = "0.1.11";
    tokio_io = "0.1.4";
    tokio_service = "0.1.0";
  };
  deps.tokio_service."0.1.0" = {
    futures = "0.1.17";
  };
  deps.unicase."2.1.0" = {
    version_check = "0.1.3";
  };
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.0.4" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.vec_map."0.8.1" = {};
  deps.version_check."0.1.3" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.3" = {
    winapi_i686_pc_windows_gnu = "0.3.2";
    winapi_x86_64_pc_windows_gnu = "0.3.2";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.3.2" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.3.2" = {};
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
}
